### ISSUE TITLE
update app version image gone

### ISSUE THREAD

**Issue by aofeng2009** [kfiroo/react-native-cached-image#83] opened 2017-09-19 03:37 UTC
When i cover install my app, I found many images gone. On my last version '1.3.5' everything is ok.

```
import { CachedImage } from 'react-native-cached-image'
....
<CachedImage source={{uri: imageurl}} style={{width:screenWidth, height:screenHeight}}></CachedImage>
```

**Comment by kfiroo** [comment] 2017-09-19 20:00
@aofeng2009 Hey, I'm not sure I understand.
Can you provide more info?

**Comment by ovaris** [comment] 2017-09-20 15:17
Try clearing the cache, I had similar problem

**Comment by aofeng2009** [comment] 2017-09-22 07:19
@ovaris But when we make an update ,we should not clear the cache,It's useful to our app.
I dont know if this library cached image's name by app version ? @kfiroo

**Comment by tavriaforever** [comment] 2017-09-22 09:42
+1 images gone. Users couldn`t clear cache every time.

**Comment by tavriaforever** [comment] 2017-09-22 10:25
What happens in my app after update. 
Component start to found image in a right directories, found exist image but path is incorrect. 

source: `https://website_cdn_host.com/n_files/24/11/10000x300/foto_avtotsentra_0x0.jpg`

![react native debugger - connected port 8081 2017-09-22 13-20-40](https://user-images.githubusercontent.com/975906/30740363-57630820-9f99-11e7-8184-d567c1b6ec0e.png)

**Comment by ovaris** [comment] 2017-09-22 11:53
We also experienced randomly disappearing images after upgrade, so for now I changed our codebase to use `Image`s until things cool down

**Comment by tavriaforever** [comment] 2017-09-22 12:23
I fixed it by additional code, I added callback to onError on `CachedImage` and if interner is available – try to reload image. It works, but seem it is a little bit hack.

```
onError = () => {
    console.log('== Imager Error, try to reload ==');
    const { source: { uri } } = this.props;

    NetInfo.isConnected.fetch().then(isConnected => {
      if (!isConnected) {
        setTimeout(() => Alert.alert('Отсутствует интернет соединение'), 100);
        return;
      }

      this.getImageCacheManager().deleteUrl(uri)
        .then(() => {
          console.log('delete url from cache');
          this.getImageCacheManager()
            .downloadAndCacheUrl(uri)
            .then(cachedImagePath => {
              console.log('== Imager reload ==');
              this.setState({
                imagePath: cachedImagePath,
              });
            });
        });
    });
  }
```

**Comment by kfiroo** [comment] 2017-09-26 15:15
@ovaris @aofeng2009 @tavriaforever 
Hey guys,
I'd really like to get to the bottom of this, I'll need your help with some info.

With the new version we introduced a cache manager with cache-policies and cached urls expirations.
Previously a url was present in the cache if there was a file in its corresponding file path location, as calculated by the code. 
Now, a url is present in the cache if the `cacheableUrl` is found in the cache manager (`MemoryCache` by default`).

This means that all urls would be re-downloaded and added to the new cache system, so I don't see why things shouldn't work smoothly, just as a fresh install would.

If you have any more info or a simple use-case that reproduces the issue it would be of great help!

Thanks

**Comment by keske** [comment] 2017-09-26 17:46
Hello there,

After update the module I had the same issue. I've removed my application from simulator (iOS) and from the device (iPhone) re-built it and now all images show fine.

**Comment by aofeng2009** [comment] 2017-09-30 09:32
@kfiroo After debuging I found the problem caused by new memory cache feature.
We know that when freshing install iOS app, the sandbox path of our app  maybe changed. But now here's code  still used  the last sandbox path as image path.  I make a PR https://github.com/kfiroo/react-native-cached-image/pull/91. I do not know if it is designed correctly .Please check. Thank you. @tavriaforever @ovaris @keske

**Comment by augustbjornberg** [comment] 2017-10-05 01:45
What is the status on this and #91 ? Thanks for the update @aofeng2009 .

Package is currently broken, i can't push my app to the app store because i know my users images wont load if they install the update.

**Comment by kozillla** [comment] 2017-10-05 09:06
Hello there,

I am experiencing the same issue.
If i upgrade (IOS) my app version, all images are gone. Restarting app do not help.Only way to see them back is to delete and reinstall app, which might be quite annoying for users in prod environment.

**Comment by aofeng2009** [comment] 2017-10-05 12:41
@augustbjornberg I was waiting for kfiroo checking my request。

**Comment by kfiroo** [comment] 2017-10-05 17:37
@aofeng2009 @kozillla @augustbjornberg @keske Hey all,
Sorry I'm not responsive, currently in Mexico heading to Belize so internet (and time in front of a computer) is not a common thing :)

I promise I'll try to take a look at the PR and provide a fix in the following week or so.

Thanks for your patience

**Comment by chrusart** [comment] 2017-10-18 08:40
I put my two cents in PR #91 :)

**Comment by chrusart** [comment] 2017-10-18 08:45
@tavriaforever is really not a resolution for this issue, problem is deeper in the cached-image library, internet connection errors have nothing to do here. It works only because when internet is back and url cache is deleted (which was wrong after app id changed), new one is created with correct app id and file downloaded again, but the file is there, just path is wrong.

**Comment by kfiroo** [comment] 2017-10-20 15:13
Is this resolved by https://github.com/kfiroo/react-native-cached-image/pull/97?

**Comment by tavriaforever** [comment] 2017-10-20 16:04
I will check it tomorrow

**Comment by tavriaforever** [comment] 2017-10-20 16:39
I added into my package.json last commit in #97 
```
"react-native-cached-image": "github:flatfox-ag/react-native-cached-image#d8e1ddd5d1f5cc3213457a05d4ef74c4ec4ea959",
```

and now bug is gone! 🎉  It`s great, thanks a lot colleagues!

**Comment by kfiroo** [comment] 2017-10-20 21:55
@tavriaforever Awesome :)
I published `v1.4.2` with the fix

**Closed by kfiroo** 2017-10-20 21:55 UTC
